#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx eslint --fix . &&
npm run lint &&
echo "✅ eslint finished successfully" &&
npx prettier --write --ignore-unknown . &&
npx prettier --check . &&
echo "✅ Prettier finished successfully"
