name: Github Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: false
      - run: npm ci
      - run: npm run build:docs
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
